### ISSUE TITLE
On the 'Guitar' page, + is missing to select chords

### ISSUE THREAD

**Issue by matv1** [t-mon/guitar-tools#4]
On the Xenial version, there is no way to select chords, as there is no plus sign in the menu, like there was in the original version.

**Comment by matv1** [comment]
apparently, this has for some reason been actively been removed at one point. the lines have been commented out on the GuitarPlayerPage.qml lines 63-66 should be re-added
```
//            Action {
//                iconName: "add"
//                onTriggered: PopupUtils.open(chordSelectionComponent)
//            },
```

**Comment by matv1** [comment]
actually, the fret-board icon is also missing. In fact it seems the whole pageheader section was copied from the guitar tuner page. Probably by mistake?

**Comment by t-mon** [comment]
Hi! Thanks for the bug report! I'll fix this today! 

Looking at my own commits this happened probably when I started to migrate to the QtQuick controls 2!

**Comment by t-mon** [comment]
I just released the fix to the open store.
