### ISSUE TITLE
Publish arm64 and amd64 architectures to the OpenStore

### ISSUE THREAD

**Issue by krille-chan** [t-mon/guitar-tools#8]
Now it is possible to publish more architectures to the OpenStore.

**Comment by jonnius** [comment]
Doing so is easy:

- [ ] Merge #9 
- [ ] Make sure you Clickable is up-to-date (should be >= 6.9.1)
- [ ] Make sure your Clickable images are up-to-date with `clickable update`
- [ ] Build for all architectures
```
clickable build --arch armhf
clickable build --arch arm64
clickable build --arch amd64
```
- [ ] Publish for all architectures
```
clickable publish --arch armhf --apikey <OPENSTORE_KEY>
clickable publish --arch arm64 --apikey <OPENSTORE_KEY>
clickable publish --arch amd64 --apikey <OPENSTORE_KEY>
```

**Comment by t-mon** [comment]
Hmm, I'm currently not allowed to upload. Am I doing something wrong?

    $ clickable build --arch arm64
    ....
    Successfully built package in './guitar-tools.t-mon_0.5.4_arm64.click'.

When I try to upload...

    $ clickable publish --arch arm64 --apikey *****************************
    Uploading version 0.5.4 of guitar-tools.t-mon for xenial/arm64 to the OpenStore
    Failed to upload click: There was an error updating your app, please try again later

**Comment by t-mon** [comment]
Hmm, I'm currently not allowed to upload. Am I doing something wrong?

    $ clickable build --arch arm64
    ....
    Successfully built package in './guitar-tools.t-mon_0.5.4_arm64.click'.

When I try to upload...

    $ clickable publish --arch arm64 --apikey *****************************
    Uploading version 0.5.4 of guitar-tools.t-mon for xenial/arm64 to the OpenStore
    Failed to upload click: There was an error updating your app, please try again later

> Note: Same for `amd64`

**Comment by jonnius** [comment]
There are some upload issues on OpenStore lately. Usually you only need to try again later. Alternatively you can upload them manually via the website.

**Comment by t-mon** [comment]
Ok, it worked now and should be online. Thanks for the hint!

**Comment by jonnius** [comment]
Works fine. Thanks!
